<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LotesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('lotes')->insert([
            [
                'idPredio' => 1,
                'manzana' => 1,
                'lote' => 1,
                'descripcion' => 'Lote regular cerca de la entrada principal.',
                'regular' => true,
                'donacion' => false,
                'loteComercial' => false,
                'loteReparable' => false,
                'loteReparableObs' => '',
                'inhabilitado' => false,
                'metrosFrente' => 30.00,
                'metrosAtras' => 30.00,
                'metrosDerecho' => 50.00,
                'metrosIzquierda' => 50.00,
                'metrosCuadrados' => 1500.00,
                'precio' => 191000.00,
                'plazoMeses' => 12,
                'pagoMensual' => 15916.67,
                'estatusPago' => 'pendiente',
            ],
            [
                'idPredio' => 1,
                'manzana' => 1,
                'lote' => 2,
                'descripcion' => 'Lote esquinero con fácil acceso.',
                'regular' => true,
                'donacion' => false,
                'loteComercial' => false,
                'loteReparable' => false,
                'loteReparableObs' => '',
                'inhabilitado' => false,
                'metrosFrente' => 30.00,
                'metrosAtras' => 30.00,
                'metrosDerecho' => 50.00,
                'metrosIzquierda' => 50.00,
                'metrosCuadrados' => 1500.00,
                'precio' => 199400.00,
                'plazoMeses' => 12,
                'pagoMensual' => 16616.67,
                'estatusPago' => 'pendiente',
            ],
            [
                'idPredio' => 1,
                'manzana' => 1,
                'lote' => 3,
                'descripcion' => 'Lote cerca de áreas verdes.',
                'regular' => true,
                'donacion' => false,
                'loteComercial' => false,
                'loteReparable' => false,
                'loteReparableObs' => '',
                'inhabilitado' => false,
                'metrosFrente' => 28.00,
                'metrosAtras' => 28.00,
                'metrosDerecho' => 48.00,
                'metrosIzquierda' => 48.00,
                'metrosCuadrados' => 1344.00,
                'precio' => 175200.00,
                'plazoMeses' => 12,
                'pagoMensual' => 14600.00,
                'estatusPago' => 'pendiente',
            ],
            [
                'idPredio' => 1,
                'manzana' => 2,
                'lote' => 4,
                'descripcion' => 'Lote comercial ideal para negocios.',
                'regular' => true,
                'donacion' => false,
                'loteComercial' => true,
                'loteReparable' => false,
                'loteReparableObs' => '',
                'inhabilitado' => false,
                'metrosFrente' => 32.00,
                'metrosAtras' => 32.00,
                'metrosDerecho' => 52.00,
                'metrosIzquierda' => 52.00,
                'metrosCuadrados' => 1664.00,
                'precio' => 220000.00,
                'plazoMeses' => 12,
                'pagoMensual' => 18333.33,
                'estatusPago' => 'pendiente',
            ],
            [
                'idPredio' => 1,
                'manzana' => 2,
                'lote' => 5,
                'descripcion' => 'Lote regular en área residencial.',
                'regular' => true,
                'donacion' => false,
                'loteComercial' => false,
                'loteReparable' => false,
                'loteReparableObs' => '',
                'inhabilitado' => false,
                'metrosFrente' => 29.00,
                'metrosAtras' => 29.00,
                'metrosDerecho' => 49.00,
                'metrosIzquierda' => 49.00,
                'metrosCuadrados' => 1421.00,
                'precio' => 195000.00,
                'plazoMeses' => 12,
                'pagoMensual' => 16250.00,
                'estatusPago' => 'pendiente',
            ],
            [
                'idPredio' => 1,
                'manzana' => 3,
                'lote' => 6,
                'descripcion' => 'Lote con acceso a todos los servicios.',
                'regular' => true,
                'donacion' => false,
                'loteComercial' => false,
                'loteReparable' => false,
                'loteReparableObs' => '',
                'inhabilitado' => false,
                'metrosFrente' => 31.00,
                'metrosAtras' => 31.00,
                'metrosDerecho' => 51.00,
                'metrosIzquierda' => 51.00,
                'metrosCuadrados' => 1581.00,
                'precio' => 205000.00,
                'plazoMeses' => 12,
                'pagoMensual' => 17083.33,
                'estatusPago' => 'pendiente',
            ],
            [
                'idPredio' => 2,
                'manzana' => 1,
                'lote' => 7,
                'descripcion' => 'Lote en zona céntrica.',
                'regular' => true,
                'donacion' => false,
                'loteComercial' => false,
                'loteReparable' => false,
                'loteReparableObs' => '',
                'inhabilitado' => false,
                'metrosFrente' => 30.00,
                'metrosAtras' => 30.00,
                'metrosDerecho' => 50.00,
                'metrosIzquierda' => 50.00,
                'metrosCuadrados' => 1500.00,
                'precio' => 185000.00,
                'plazoMeses' => 12,
                'pagoMensual' => 15416.67,
                'estatusPago' => 'pendiente',
            ],
            [
                'idPredio' => 2,
                'manzana' => 2,
                'lote' => 8,
                'descripcion' => 'Lote con vista al parque.',
                'regular' => true,
                'donacion' => false,
                'loteComercial' => false,
                'loteReparable' => false,
                'loteReparableObs' => '',
                'inhabilitado' => false,
                'metrosFrente' => 28.00,
                'metrosAtras' => 28.00,
                'metrosDerecho' => 48.00,
                'metrosIzquierda' => 48.00,
                'metrosCuadrados' => 1344.00,
                'precio' => 178000.00,
                'plazoMeses' => 12,
                'pagoMensual' => 14833.33,
                'estatusPago' => 'pendiente',
            ],
            [
                'idPredio' => 2,
                'manzana' => 3,
                'lote' => 9,
                'descripcion' => 'Lote cercano a área comercial.',
                'regular' => true,
                'donacion' => false,
                'loteComercial' => false,
                'loteReparable' => false,
                'loteReparableObs' => '',
                'inhabilitado' => false,
                'metrosFrente' => 30.00,
                'metrosAtras' => 30.00,
                'metrosDerecho' => 50.00,
                'metrosIzquierda' => 50.00,
                'metrosCuadrados' => 1500.00,
                'precio' => 193000.00,
                'plazoMeses' => 12,
                'pagoMensual' => 16083.33,
                'estatusPago' => 'pendiente',
            ],
            [
                'idPredio' => 2,
                'manzana' => 4,
                'lote' => 10,
                'descripcion' => 'Lote con acceso directo a la calle principal.',
                'regular' => true,
                'donacion' => false,
                'loteComercial' => true,
                'loteReparable' => false,
                'loteReparableObs' => '',
                'inhabilitado' => false,
                'metrosFrente' => 32.00,
                'metrosAtras' => 32.00,
                'metrosDerecho' => 52.00,
                'metrosIzquierda' => 52.00,
                'metrosCuadrados' => 1664.00,
                'precio' => 220000.00,
                'plazoMeses' => 12,
                'pagoMensual' => 18333.33,
                'estatusPago' => 'pendiente',
            ],
        ]);
    }
}
